<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintBoolean.jsp" label="positivePrintBooleanTest">
  <validate>
    <!--TEST STRATEGY: Call print(boolean b) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintBoolean.html" ignoreWhitespace="true" label="JspWriter.print(boolean b) will print the String produced by java.lang.String.valueOf(boolean).  The byte's displayed will be according to the platform's default character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintChar.jsp" label="positivePrintCharTest">
  <validate>
    <!--TEST STRATEGY: Call print(char c) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintChar.html" ignoreWhitespace="true" label="JspWriter.print(char c) prints passed value according to the platform's default character encoding. Server Pages Specification v1.2, Sec 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintCharArray.jsp" label="positivePrintCharArrayTest">
  <validate>
    <!--TEST STRATEGY: Call print(char[] c) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintCharArray.html" ignoreWhitespace="true" label="JspWriter.print(char[] s) will print an array of characters according to the platform's default  character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintDouble.jsp" label="positivePrintDoubleTest">
  <validate>
    <!--TEST STRATEGY: Call print(double d) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintDouble.html" ignoreWhitespace="true" label="JspWriter.print(double d) prints a String representation of a double-precision floating-point number, generated by  java.lang.String.valueOf(double), with the bytes translated to the platform's default character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintFloat.jsp" label="positivePrintFloatTest">
  <validate>
    <!--TEST STRATEGY: Call print(float f) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintFloat.html" ignoreWhitespace="true" label="JspWriter.print(float f) prints a String representation of a floating point number, generated by java.lang.String.valueOf(float), with the bytes translated to the platform's default character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintInt.jsp" label="positivePrintIntTest">
  <validate>
    <!--TEST STRATEGY: Call print(int i) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintInt.html" ignoreWhitespace="true" label="JspWriter.print(int i) prints a String representation of an integer, generated by java.lang.String.valueOf(int),  with the bytes translated to the platform's default  character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintLong.jsp" label="positivePrintLongTest">
  <validate>
    <!--TEST STRATEGY: Call print(long l) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintLong.html" ignoreWhitespace="true" label="JspWriter.print(long l) prints a String representation of a long integer, generated by java.lang.String.valueOf(long),  with the bytes translated to the platform's default  character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintObj.jsp" label="positivePrintObjTest">
  <validate>
    <!--TEST STRATEGY: Call print(java.lang.Object obj) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintObj.html" ignoreWhitespace="true" label="JspWriter.print(java.lang.Object obj) prints a String  representation of an object, generated by  java.lang.String.valueOf(Object), with the bytes translated  to the platform's default character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintStr.jsp" label="positivePrintStrTest">
  <validate>
    <!--TEST STRATEGY: Call print(java.lang.String str) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintStr.html" ignoreWhitespace="true" label="JspWriter.print(java.lang.String str) prints a String  representation of an object, with the bytes translated  to the platform's default character encoding. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintln.jsp" label="positivePrintlnTest">
  <validate>
    <!--TEST STRATEGY: Call println() and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintln.html" ignoreWhitespace="true" label="JspWriter.println() will terminate the current line by writing the ling separator string. JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnBoolean.jsp" label="positivePrintlnBooleanTest">
  <validate>
    <!--TEST STRATEGY: Call println(boolean b) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnBoolean.html" ignoreWhitespace="true" label="JspWriter.println(boolean b) prints a boolean value and then terminates the line.  This method behaves as though it invokes print(boolean b) and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnChar.jsp" label="positivePrintlnCharTest">
  <validate>
    <!--TEST STRATEGY: Call println(char c) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnChar.html" ignoreWhitespace="true" label="JspWriter.println(char c) prints a char value and then terminates the line.  This method behaves as though it invokes print(char c) and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnCharArray.jsp" label="positivePrintlnCharArrayTest">
  <validate>
    <!--TEST STRATEGY: Call println(char c) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnCharArray.html" ignoreWhitespace="true" label="JspWriter.println(char[] s) prints an array of characters and then terminates the line.  This method behaves as though it invokes print(char[] s) and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnDouble.jsp" label="positivePrintlnDoubleTest">
  <validate>
    <!--TEST STRATEGY: Call println(double d) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnDouble.html" ignoreWhitespace="true" label="JspWriter.println(double d) prints a double-precision floating-point value and then terminates the line.   This method behaves as though it invokes print(double d)  and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnFloat.jsp" label="positivePrintlnFloatTest">
  <validate>
    <!--TEST STRATEGY: Call println(float f) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnFloat.html" ignoreWhitespace="true" label="JspWriter.println(float f) prints a floating-point value  and then terminates the line.  This method behaves as though  it invokes print(float f) and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnInt.jsp" label="positivePrintlnIntTest">
  <validate>
    <!--TEST STRATEGY: Call println(int i) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnInt.html" ignoreWhitespace="true" label="JspWriter.println(int i) prints an integer value  and then terminates the line.  This method behaves as though  it invokes print(int i) and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnLong.jsp" label="positivePrintlnLongTest">
  <validate>
    <!--TEST STRATEGY: Call println(long l) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnLong.html" ignoreWhitespace="true" label="JspWriter.println(long l) prints a long integer value  and then terminates the line.  This method behaves as though  it invokes print(long l) and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnObj.jsp" label="positivePrintlnObjTest">
  <validate>
    <!--TEST STRATEGY: Call println(java.lang.Object obj) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnObj.html" ignoreWhitespace="true" label="JspWriter.println(java.lang.Object obj) prints an Object  value and then terminates the line.  This  method behaves as though it invokes print(java.lang.Object obj)  and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

<request followRedirects="false" version="1.0" path="/jsp-tests/jsp/engine/JspWriter/print/positivePrintlnStr.jsp" label="positivePrintlnStrTest">
  <validate>
    <!--TEST STRATEGY: Call println(java.lang.String str) and validate the result.-->
    <goldenFile fileName="${jsp-wgdir}/engine/JspWriter/print/positivePrintlnStr.html" ignoreWhitespace="true" label="JspWriter.println(java.lang.String str) prints a long  integer value and then terminates the line.  This  method behaves as though it invokes print(java.lang.String str)  and then println(). JavaServer Pages Specification v1.2, Sec. 9.2.2" />
  </validate>
</request>

