package org.apache.watchdog;

import java.io.InputStream;
import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.net.URL;

import java.util.Properties;

import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

import org.apache.commons.latka.Latka;
import org.apache.commons.latka.LatkaException;
import org.apache.commons.latka.LatkaProperties;
import org.apache.commons.latka.Suite;
import org.apache.commons.latka.XMLReporter;

import org.jdom.DocType;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.EntityRef;
import org.jdom.output.XMLOutputter;

public class Watchdog {

    public static void main(String args[]) throws Exception {

        Watchdog watchdog = new Watchdog();
        if (args.length == 1) {
            watchdog.runTests(args[0]);
        } else {
            watchdog.runTests();
        }

    }

    protected Properties getWatchdogProps() throws IOException {
        Properties watchdogProps = loadPropsFromClasspath("watchdog.properties");
        return watchdogProps;
    }

    protected void runTests(String entityName) throws LatkaException {
        try {
            Properties watchdogProps = getWatchdogProps();
            String dtdLocation = 
                watchdogProps.getProperty("org.apache.watchdog.dtdURL");
            
            Element suiteElement = new Element("suite");
            suiteElement.setAttribute("defaultHost","${host}");
            suiteElement.setAttribute("defaultPort","${port}");
            EntityRef ref = new EntityRef(entityName);
            suiteElement.addContent(ref);

            DocType type = new DocType("suite",dtdLocation);

            Document doc = new Document(suiteElement,type);
                        
            XMLOutputter outputter = new XMLOutputter("  ", true);
            String xmlDoc = outputter.outputString(doc);

            System.out.println(xmlDoc);

            StringReader reader = new StringReader(xmlDoc);
            Suite suite = new Suite(reader);
            runTests(suite,watchdogProps);

        } catch (IOException e) {
            throw new LatkaException(e.toString());
        }
    }

    protected void runTests() throws LatkaException {
        Properties watchdogProps = null;
        try {
            watchdogProps = getWatchdogProps();

            String suiteLocation = 
                watchdogProps.getProperty("org.apache.watchdog.mainSuiteURL");

            URL url = new URL(suiteLocation);
            Suite suite = new Suite(url);

            runTests(suite, watchdogProps);
        } catch (IOException e) {
            throw new LatkaException(e.toString());
        }
    }

    protected void runTests(Suite suite, Properties watchdogProps) throws LatkaException {
        Latka latka = new Latka();

        try {
            // add props to the Latka session
            LatkaProperties.getProperties().putAll(watchdogProps);

            XMLReporter listener = new XMLReporter();
            latka.runTests(suite,listener);

            String xml = listener.getDocumentAsString();

            System.out.println(transformXML(xml));
        } catch (IOException e) {
            throw new LatkaException(e.toString());
        }
    }



    /**
 * Load properties specified from context class path
 * @param classpathLocation Resource name to load
 * @throws IOException from loading resource
 * @return initialized properties object
 */
    protected Properties
    loadPropsFromClasspath(String classpathLocation)
    throws IOException {
        Properties properties  = new Properties();

        ClassLoader loader = Thread.currentThread().getContextClassLoader();

        InputStream stream = loader.getResourceAsStream(classpathLocation);

        if (stream == null) {
            throw new IOException("Could not find this file in classpath: "
                                  + classpathLocation);
        }

        properties.load(stream);

        return properties;
    }

    /**
     * Transform the XML generated by the XMLReporter using
     * the default stylesheet.
     *
     * @param xml XML generated by XMLReporter
     * @return transformed report
     * @throws LatkaException if the XML could not be transformed
     */
    private String transformXML(String xml) throws LatkaException {
    
        try {
            StringWriter output = new StringWriter();

            Source xslSource = null;

            ClassLoader loader = Thread.currentThread().getContextClassLoader();

            xslSource = new StreamSource(
                            loader.getResourceAsStream(
                            "org.apache.commons.latka.report.xsl")
                        );

            Transformer transformer = 
            TransformerFactory.newInstance().newTransformer(xslSource);
            StreamSource xmlSource = new StreamSource(new StringReader(xml));
            StreamResult result = new StreamResult(output);
            transformer.transform(xmlSource, result);
            return output.toString();
        } catch (TransformerException e) {
            throw new LatkaException(e);
        }
    }

}
