#!/bin/sh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

${SCRIPT_DIR}/do-prepare-dir

## Try to keep the log file XML-like, so we can XSL-extract
# usefull info from it
echo "<build-report>" > $TLOGFILE
echo "<build-id>$TDSTRING</build-id>"  >> $TLOGFILE    
## echo "<platform>" `uname -a` "</platform>" >> $TLOGFILE
echo "<hostname>$HOSTNAME</hostname>" >> $TLOGFILE
echo "<hosttype>$HOSTTYPE</hosttype>" >> $TLOGFILE
echo "<ostype>$OSTYPE</ostype>" >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-checkout 2>&1 >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-build 2>&1 >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-build-test 2>&1 >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-build-apache1.3 2>&1 >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-test 2>&1 >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-package 2>&1 >> $TLOGFILE

echo "</build-report>" >> $TLOGFILE





