#!/bin/sh

export BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

${SCRIPT_DIR}/do-prepare-dir

## Try to keep the log file XML-like, so we can XSL-extract
# usefull info from it
echo "<build-report>" > $TLOGFILE
echo "<build-id>$TDSTRING</build-id>"  >> $TLOGFILE    
## echo "<platform>" `uname -a` "</platform>" >> $TLOGFILE
echo "<hostname>$HOSTNAME</hostname>" >> $TLOGFILE
echo "<hosttype>$HOSTTYPE</hosttype>" >> $TLOGFILE
echo "<ostype>$OSTYPE</ostype>" >> $TLOGFILE

# echo $TSEP | cat >> $TLOGFILE
${SCRIPT_DIR}/do-checkout 

# echo $TSEP | cat >> $TLOGFILE
${SCRIPT_DIR}/do-build >> $TLOGFILE

# echo $TSEP | cat >> $TLOGFILE
${SCRIPT_DIR}/do-test >> $TLOGFILE

${SCRIPT_DIR}/do-package 

echo "</build-report>" >> $TLOGFILE





