#!/bin/sh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

## Try to keep the log file XML-like, so we can XSL-extract
# usefull info from it
echo "<build-report>" > $TLOGFILE
echo "<build-start>" `date` "</build-start>"  >> $TLOGFILE    
echo "<build-id>$TDSTRING</build-id>"  >> $TLOGFILE    
## echo "<platform>" `uname -a` "</platform>" >> $TLOGFILE
echo "<hostname>$HOSTNAME</hostname>" >> $TLOGFILE
echo "<hosttype>$HOSTTYPE</hosttype>" >> $TLOGFILE
echo "<ostype>$OSTYPE</ostype>" >> $TLOGFILE

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-build-tomcat >> $TLOGFILE 2>&1 

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-build-test >> $TLOGFILE 2>&1 

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-build-apache1.3 >> $TLOGFILE 2>&1 

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-test >> $TLOGFILE 2>&1 

echo  >> $TLOGFILE
echo  >> $TLOGFILE
${SCRIPT_DIR}/do-package  >> $TLOGFILE  2>&1

echo "<build-end>" `date` "</build-end>"  >> $TLOGFILE    
echo "</build-report>" >> $TLOGFILE





