#!/bin/ksh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

echo "<build name=\"jakarta-tomcat-test\">"
cd ${SRC_DIR}/jakarta-tomcat
sh build.sh test
echo "</build>"

echo "<build name=\"jakarta-watchdog\">"
cd ${SRC_DIR}/jakarta-watchdog
sh build.sh dist
echo "</build>"


