#!/bin/sh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

echo "<checkout>"
cd ${BUILD_DIR}/ws

    # filter out boring messages
cvs -d $CVSROOT checkout \
		jakarta-tools \
		jakarta-tomcat \
		jakarta-watchdog \
		apache-1.3 \
		apache-2.0 2>&1 \
		| grep -v "cvs server: Updating" \
		| grep -v "U "

echo "</checkout>"