#!/bin/sh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

echo PACKAGE:

cd ${SRC_DIR}/dist/tomcat

tar cf ${BUILD_DIR}/result/tomcat-$TDSTRING.tar *
cd ${BUILD_DIR}/result
compress -f tomcat-$TDSTRING.tar

cd ${APACHE_HOME}
tar cf ${BUILD_DIR}/result/apache-1.3.9-${HOSTTYPE}-${OSTYPE}.tar *
cd ${BUILD_DIR}/result
compress -f apache-1.3.9-${HOSTTYPE}-${OSTYPE}.tar

cp ${APACHE_HOME}/libexec/mod_ajp23.so .
compress -f mod_ajp23.so
mv mod_ajp23.so.Z mod_ajp23-${HOSTTYPE}-${OSTYPE}-$TDSTRING.Z

cp tomcat-$TDSTRING.tar.Z $FTP_DIR
cp tomcat-${HOSTTYPE}-${OSTYPE}-$TDSTRING.log $FTP_DIR
cp apache-1.3.9-${HOSTTYPE}-${OSTYPE}.tar.Z $FTP_DIR
cp mod_ajp23-${HOSTTYPE}-${OSTYPE}-${TDSTRING}.Z $FTP_DIR
cp mod_ajp23-${HOSTTYPE}-${OSTYPE}-${TDSTRING}.Z $FTP_DIR

cp ${SRC_DIR}/jakarta-tomcat/src/native/apache/jserv/mod_jserv.so ${FTP_DIR}/mod_jserv-${HOSTTYPE}-${OSTYPE}.so
