#!/bin/ksh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

echo "<test name=\"jakarta-tomcat\">"
cd ${BUILD_DIR}/ws/build/tomcat/test
sh runtest.sh
echo "</test>"

echo "<test name=\"jakarta-watchdog\">"
cd ${BUILD_DIR}/ws/build/watchdog
sh runtest.sh
echo "</test>"


