#!/bin/sh

BASEDIR=`dirname $0`
. ${BASEDIR}/env-client

echo "<update>"
cd ${SRC_DIR}

    # filter out boring messages
for i in jakarta-tools jakarta-tomcat jakarta-watchdog apache-1.3 apache-2.0
do
   echo Updating $i
  ( cd $i ; cvs -d $CVSROOT update -d ) 2>&1 \
		| grep -v "cvs server: Updating" \
		| grep -v "U "
done

echo "</update>"