#!/bin/bash

# This is the script that is run on taz every night to collect the
# builds from various locations

export TDSTRING=`date +%Y``date +%m``date +%d`

# Get Canonical Unix build
cd /x3/www/jakarta.apache.org/builds/tomcat/standalone/nightly

ftp ftp://tokyo.javasoft.com/pub/tomcat/tomcat-$TDSTRING.tar.Z
ftp ftp://tokyo.javasoft.com/pub/tomcat/tomcat-sun4u-SunOS-$TDSTRING.log

# Get Canoncial Windows build


## Post processing
# cat tomcat-sparc-solaris2.4-$TDSTRING.log | mail -s "Unix Standalone Build $TDSTRING" tomcat-dev@jakarta.apache.org 
cat tomcat-sun4u-SunOS-$TDSTRING.log | mail -s "Unix Standalone Build $TDSTRING" costin@eng.sun.com

# Re-Compress of standard Java builds
uncompress -c tomcat-$TDSTRING.tar.Z >tomcat-$TDSTRING.tar
bzip2 --stdout tomcat-$TDSTRING.tar > tomcat-$TDSTRING.tar.bz2
uncompress -c tomcat-$TDSTRING.tar.Z |  gzip -c tomcat-$TDSTRING.tar.gz


# Get Integrated Builds
cd /x3/www/jakarta.apache.org/builds/tomcat/integrated/nightly

# Solaris Sparc
ftp ftp://tokyo.javasoft.com/pub/tomcat/apache-1.3.9-sun4u-SunOS.tar.Z
ftp ftp://tokyo.javasoft.com/pub/tomcat/mod_ajp23-sun4u-SunOS-${TDSTRING}.Z  

# Solaris Intel

# Linux Sparc
ftp ftp://kyoto.javasoft.com/pub/tomcat/tomcat-sparc64-Linux-$TDSTRING.log
ftp ftp://kyoto.javasoft.com/pub/tomcat/apache-1.3.9-sparc64-Linux.tar.Z
ftp ftp://kyoto.javasoft.com/pub/tomcat/mod_ajp23-sparc64-Linux-${TDSTRING}.Z  

# Linux Intel
ftp ftp://osaka.javasoft.com/pub/tomcat/tomcat-i686-Linux-$TDSTRING.log
ftp ftp://osaka.javasoft.com/pub/tomcat/apache-1.3.9-i686-Linux.tar.Z
ftp ftp://osaka.javasoft.com/pub/tomcat/mod_ajp23-i686-Linux-${TDSTRING}.Z  

# FBSD Intel

