#!/bin/bash

# This is the script that is run on taz every night to collect the
# builds from various locations

export TYEAR=`date +%Y`
export TMONTH=`date +%m`
export TDAY=`date +%d`
export TDSTRING=$TYEAR-$TMONTH-$TDAY

cd /x3/www/jakarta.apache.org/builds/tomcat/standalone/nightly

# Get Canonical Unix build

ftp ftp://tokyo.javasoft.com/pub/tomcat/tomcat-sparc-solaris2.4-$TDSTRING.log
ftp ftp://tokyo.javasoft.com/pub/tomcat/tomcat-$TDSTRING.tar.Z

# Get Canoncial Windows build

# Get Integrated Builds

# Solaris Sparc

# Solaris Intel

# Linux Sparc
ftp ftp://kyoto.javasoft.com/pub/tomcat/tomcat-sparc-Linux-$TDSTRING.log
ftp ftp://kyoto.javasoft.com/pub/tomcat/apache-1.3.9-sparc-Linux.tar.Z
ftp ftp://kyoto.javasoft.com/pub/tomcat/mod_ajp23-sparc-Linux-${TDSTRING}.Z  

# Linux Intel
ftp ftp://osaka.javasoft.com/pub/tomcat/tomcat-i386-Linux-$TDSTRING.log
ftp ftp://osaka.javasoft.com/pub/tomcat/apache-1.3.9-i386-Linux.tar.Z
ftp ftp://osaka.javasoft.com/pub/tomcat/mod_ajp23-i386-Linux-${TDSTRING}.Z  

# FBSD Intel

# Windows NT



## Post processing
cat tomcat-sparc-solaris2.4-$TDSTRING.log | mail -s "Unix Standalone Build $TDSTRING" tomcat-dev@jakarta.apache.org 

# XXX mv tomcat-$TDSTRING.log tomcat-$TDSTRING-sparc-sol-7-jdk117.log

# Re-Compress of standard Java builds
cp tomcat-$TDSTRING.tar.Z tomcat-foo.tar.Z
uncompress tomcat-foo.tar.Z
mv tomcat-foo.tar tomcat-$TDSTRING.tar
bzip2 --stdout tomcat-$TDSTRING.tar > tomcat-$TDSTRING.bz2
gzip tomcat-$TDSTRING.tar

