<html>
<title>positiveErrorPage</title>
<body>
<% /** 	Name : positiveErrorPage
	Description : Here, the errorPage directive is used.An exception is
	generated by dividing an integer value by 0.
	Result :Expected to show the specified errorpage.
**/ %>	 
<!--we are setting the error page to errorpage.jsp where iserrorpage is true ->
<%@ page errorPage="myErrorpage.jsp" autoFlush="false" %>
<%! int i=0; %>
<%= 9/i %>
</body>
</html>